export const studentData = [
  {
    studentName:"abimran23",
    frontImg:"/img/imranfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"imran",
    certificates:[
      {
        img:'/certificat/imrancertificate1.jpg'
      },
    ]
  },
  {
    studentName:"maogtay21",
    frontImg:"/img/ogtayfront.png",
    backImg:"/img/oqtayback.jpg",
    resBackImg:"/img/oqtaybackphone.jpg",
    className:"oqtay",
    certificates:[
      {
        img:'/certificat/oqtaycertificate1.jpg'
      },
    ]
  },
  {
    studentName:"khraul19",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"khfarkhan29",
    frontImg:"/img/farxanfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mamurad05",
    frontImg:"/img/muradfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alidris27",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"azdavud06",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rakabira07",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rafarahnaz11",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
]
