export const studentData = [
  {
    studentName:"abimran23",
    frontImg:"/img/imranfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"imran",
    certificates:[
      {
        img:'/certificat/imrancertificate1.jpg'
      },
      {
        img:'/certificat/imrancertificate2.jpg'
      },
    ]
  },
  {
    studentName:"maogtay21",
    frontImg:"/img/oqtayfront.png",
    backImg:"/img/oqtayback.jpg",
    resBackImg:"/img/oqtaybackphone.jpg",
    className:"oqtay",
    certificates:[
      {
        img:'/certificat/oqtaycertificate1.jpg'
      },
      {
        img:'/certificat/oqtaycertificate2.jpg'
      },
      {
        img:'/certificat/oqtaycertificat3.jpg'
      },
      {
        img:'/certificat/oqtaycertificate4.jpg'
      },
      {
        img:'/certificat/oqtaycertificate12.jpg'
      },
      {
        img:'/certificat/oqtaycertificate13.jpg'
      },
      {
        img:'/certificat/oqtaycertificate5.jpg'
      },
      {
        img:'/certificat/oqtaycertificate6.jpg'
      },
      {
        img:'/certificat/oqtaycertificate7.jpg'
      },
      {
        img:'/certificat/oqtaycertificate8.jpg'
      },
      {
        img:'/certificat/oqtaycertificate9.jpg'
      },
      {
        img:'/certificat/oqtaycertificate10.jpg'
      },
      {
        img:'/certificat/oqtaycertificate11.jpg'
      },
    ]
  },
  {
    studentName:"khraul19",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"khfarkhan29",
    frontImg:"/img/farxanfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mamurad05",
    frontImg:"/img/muradfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alidris27",
    frontImg:"/img/idrisfront.png",
    backImg:"/img/idrisback.jpg",
    resBackImg:"/img/idrisbackphone.jpg",
    className:"alidris27"
  },
  {
    studentName:"azdavud06",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rakabira07",
    frontImg:"/img/kabirafront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rafarahnaz11",
    frontImg:"/img/farahnazfront.png",
    backImg:"/img/farahnazback.jpg",
    resBackImg:"/img/farahnazbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"ibfuad27",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alayaz28",
    frontImg:"/img/ayazfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"maamir14",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"kaamina21",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mafateh12",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"dodeniz12",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"almaryam04",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alreyhana01",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"agali10",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"almuhammad20",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"kamehri28",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  // new
  {
    studentName:"alali13",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asmurad11",  
    frontImg:"/img/asmurad11.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"maheydar15",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asadelina19",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"betahir15",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"gurahim27",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"gusonam23",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"safuad30",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"sahuseyn17",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"avsarkhan16",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"shraul03",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asharun30",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"vailhan08",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asahmad02",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  // new 
  {
    studentName:"shraul16",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
]
