export const studentData = [
  {
    studentName:"abimran23",
    frontImg:"/img/imranfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"imran",
    certificates:[
      {
        img:'/certificat/imrancertificate1.jpg'
      },
    ]
  },
  {
    studentName:"imran",
    frontImg:"/invitationsImg/imranfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"maogtay21",
    frontImg:"/img/oqtayfront.png",
    backImg:"/img/oqtayback.jpg",
    resBackImg:"/img/oqtaybackphone.jpg",
    className:"oqtay",
    certificates:[
      {
        img:'/certificat/oqtaycertificate1.jpg'
      },
    ]
  },
  {
    studentName:"oqtay",
    frontImg:"/invitationsImg/oqtayfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"khraul19",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"raul",
    frontImg:"/invitationsImg/raulfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"khfarkhan29",
    frontImg:"/img/farxanfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"farkhan",
    frontImg:"/invitationsImg/farkhanfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"mamurad05",
    frontImg:"/img/muradfront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"murad",
    frontImg:"/invitationsImg/muradfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"alidris27",
    frontImg:"/img/idrisfront.png",
    backImg:"/img/idrisback.jpg",
    resBackImg:"/img/idrisbackphone.jpg",
    className:"alidris27"
  },
  {
    studentName:"idris",
    frontImg:"/invitationsImg/idrisfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"azdavud06",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"davud",
    frontImg:"/invitationsImg/davudfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"rakabira07",
    frontImg:"/img/kabirafront.png",
    backImg:"/img/imranback.jpg",
    resBackImg:"/img/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rafarahnaz11",
    frontImg:"/img/farahnazfront.png",
    backImg:"/img/farahnazback.jpg",
    resBackImg:"/img/farahnazbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"farahnaz",
    frontImg:"/invitationsImg/farahnazfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"ibfuad27",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"fuad",
    frontImg:"/invitationsImg/fuadfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"alayaz28",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"ayaz",
    frontImg:"/invitationsImg/ayazfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"maamir14",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"amir",
    frontImg:"/invitationsImg/amirfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"kaamina21",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"amina",
    frontImg:"/invitationsImg/aminafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"mafateh12",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"fateh",
    frontImg:"/invitationsImg/fatehfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"dodeniz12",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"deniz",
    frontImg:"/invitationsImg/denizfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"almaryam04",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"maryam",
    frontImg:"/invitationsImg/maryamfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"alreyhana01",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"reyhana",
    frontImg:"/invitationsImg/reyhanafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"agali10",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"almuhammad20",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"muhammad",
    frontImg:"/invitationsImg/muhammadfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"kamehri28",
    frontImg:"/img/raulfront.png",
    backImg:"/img/raulback.jpg",
    resBackImg:"/img/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mehri",
    frontImg:"/invitationsImg/mehrifront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },

  // cv si olmayanlar

  {
    studentName:"tahir",
    frontImg:"/invitationsImg/tahirfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"nariman",
    frontImg:"/invitationsImg/narimanfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"ali",
    frontImg:"/invitationsImg/alifront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"dilshad",
    frontImg:"/invitationsImg/dilshadfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"dilusha",
    frontImg:"/invitationsImg/dilushafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"messi",
    frontImg:"/invitationsImg/messifront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"suleyman",
    frontImg:"/invitationsImg/suleymanfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"yusif",
    frontImg:"/invitationsImg/yusiffront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"safa",
    frontImg:"/invitationsImg/safafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"bahar",
    frontImg:"/invitationsImg/baharfront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"ayla",
    frontImg:"/invitationsImg/aylafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
  {
    studentName:"gulnaz",
    frontImg:"/invitationsImg/aylafront.png",
    backImg:"/invitationsImg/imranback.jpg",
    resBackImg:"/invitationsImg/imranbackphone.jpg",
  },
]
